# NumPy

In [1]:
import numpy
numpy.__version__

'1.26.4'

## Pythonのデータ型

In [2]:
# Pythonコード
result = 0
for i in range(100):
    result += i

* pythonでは、1つの整数変数は4つの部品から構成されている

```text
    ob_refcnt
        Pythonがメモリの割り当てと解除を自動的に行うための参照カウンタ
    ob_type
        変数の型を表すコード
    ob_size
        この後に続くデータの大きさ
    ob_digit
        このPython変数が持つ実際の整数値
```


In [3]:
# Pythonの型固定配列
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 'i'は整数型

In [4]:
# numpyの型固定配列
import numpy as np
# Integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

* Pythonリストとは異なりNumPy配列の要素はすべて同じ型という制約がある
* 型が一致しない場合、可能であればNumpyはアップキャストする(下記は整数から浮動小数点数)

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
# データ型の指定
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# 多次元の配列
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### NumPy配列の作成

* 大きな配列の場合、NumPyに組み込まれた関数を使用して配列を最初から作成する方が効率的。

In [8]:
# 要素がすべて0で長さ10の整数配列を作る
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 要素がすべて1である3行5列の浮動小数点配列を作る
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 要素がすべて3.14である3行5列の配列を作る
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# 開始値0、終了値20で2ずつ増加する
# 線形シーケンス配列を作る
# (組み込みのrange()関数と同じ働きをする)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# 0と1の間に均等に配置された5つの値の配列を作る
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# 0と1の間に3行3列の一様分布疑似乱数配列を作る
np.random.random((3,3))

array([[0.13458137, 0.00779126, 0.92234625],
       [0.06235113, 0.48711669, 0.99557331],
       [0.99673269, 0.15668613, 0.68705799]])

In [14]:
# 平均値0と標準偏差1の正規分布乱数で3行3列の配列を作る
np.random.normal(0, 1, (3, 3))

array([[-0.38626166,  1.6159413 ,  0.37274606],
       [ 1.07847802,  0.3954325 ,  1.00878627],
       [ 1.15853932, -0.07672041, -1.13140944]])

In [15]:
# 区間[0, 10]のランダムな整数で3行3列の配列を作る
np.random.randint(0, 10, (3, 3))

array([[2, 6, 5],
       [5, 1, 0],
       [2, 5, 0]])

In [16]:
# 3行3列の単位行列を作る
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# 3つの整数の初期化されていない配列を作る
# 各要素の数は、そのメモリ位置に既に存在していたものになる
np.empty(3)

array([1., 1., 1.])

### NumPyの標準データ型
* NumPy配列の値はすべて同じ型
* 文字列で指定 or NumPyオブジェクトを使用する
    ```Python
    np.zeros(10, dtype='int16')
    # or
    np.zeros(10, dtype=np.int16)
    ```

* NumPyデータ型
  * 論理型
    * bool_ : 論理型(True or False) 1バイトに格納される
  * 整数型
    * int_ : デフォルトの整数型(C言語のlong)
    * intc : C言語のintと同じ
    * intp : インデクスに使用するための整数(C言語のssize_tと同様。通常int64 or int32)
    * int8 : -128から127
    * int16 : -32,768から32,767
    * int32 : -2,147,483,648から2,147,483,647
    * int64 : -9,223,372,036,854,775,808から9,223,372,036,854,775,807
  * 整数型(自然数)
    * uint8 : 0から255
    * uint16 : 0から65,535
    * uint32 : 0から4,294,967,295
    * uint64 : 0から18,446,744,073,709,551,615
  * 浮動小数点数型
    * float_ : float64の略
    * float16 : 符号部1ビット, 指数部5ビット, 仮数部10ビット
    * float32 : 符号部1ビット, 指数部8ビット, 仮数部23ビット
    * float16 : 符号部1ビット, 指数部11ビット, 仮数部52ビット


## NumPy配列の基礎

### NumPy配列の属性

In [18]:
rng = np.random.default_rng(seed=1701)  # 同じ乱数を得るために
                                        # 乱数シードを設定
x1 = rng.integers(10, size=6)           # 1次元配列
x2 = rng.integers(10, size=(3, 4))      # 2次元配列
x3 = rng.integers(10, size=(3, 4, 5))   # 3次元配列

In [19]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


* 配列は、属性としてndim(次元数)、shape(各次元のサイズ)、size(配列の合計サイズ)、dtype(要素の型)を持つ

### 配列インデクス:配列の要素にアクセスする

* Pythonリストと同様に目的のインデクスを角括弧で囲む

In [20]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [21]:
x1[0]

9

In [22]:
x1[-1]

6

In [23]:
x1[-2]

8

In [24]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [25]:
x2[0,0]

3

In [26]:
x2[2, 0]

0

In [27]:
x2[2,-1]

9

In [28]:
# インデクス表記を使用し、要素の値を変更できる
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

* Pythonリストと異なり、NumPy配列は型が固定されていることに注意すること

In [29]:
# 小数点以下が切り捨てられる
x1[0] = 3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

### 配列のスライス:部分配列にアクセスする
* NumPyでもPythonと同様にスライスでアクセスできる
```Python
    x[start:stop:step]
```

#### 1次元配列のスライス

In [30]:
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [31]:
x1[:3] # 最初の3要素

array([3, 4, 0], dtype=int64)

In [32]:
x1[3:] # インデクス3以降の要素

array([3, 8, 6], dtype=int64)

In [33]:
x1[1:4] # 中央の部分配列

array([4, 0, 3], dtype=int64)

In [34]:
x1[::2] # 1つおきの要素

array([3, 0, 8], dtype=int64)

In [35]:
x1[1::2] # インデクス1から始まる1つおきの要素

array([4, 3, 6], dtype=int64)

In [36]:
x1[::-1] # 逆順にすべての要素

array([6, 8, 3, 0, 4, 3], dtype=int64)

In [37]:
# array([3, 4, 0, 3, 8, 6], dtype=int64)
x1[4::-2] # インデクス4から逆順に1つおきの要素

array([8, 0, 3], dtype=int64)

In [42]:
# インデックス値間違えないように
x1[4]

8

#### 多次元配列のスライス

In [43]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [44]:
x2[:2, :3] # 最初の2行と3列

array([[12,  1,  3],
       [ 4,  0,  2]], dtype=int64)

In [45]:
x2[:3, ::2] # 3行と、1つおきの列

array([[12,  3],
       [ 4,  2],
       [ 0,  6]], dtype=int64)

In [46]:
x2[::-1, ::-1] # 逆順にすべての行と列

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]], dtype=int64)

* 配列のアクセスに関して、最も頻繁に行われる操作は、行または列の抽出
* 1つの：による空のスライスと目的のインデクスを組み合わせる

In [49]:
x2[:, 0] # x2の最初の列

array([12,  4,  0], dtype=int64)

In [50]:
x2[0, :] # x2の最初の行

array([12,  1,  3,  7], dtype=int64)

* 行にアクセスする場合、からのスライスを省略できる

In [51]:
x2[0] # x2[0, :]と等価

array([12,  1,  3,  7], dtype=int64)

#### コピーではなくビューである部分配列

* スライスは配列データのコピーではなくビューである点に注意すること
* NumPyとPythonの違う点の1つ
* リストはコピーを作る

In [52]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [53]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  1],
       [ 4,  0]], dtype=int64)

In [54]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [55]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

#### 配列のコピー

In [57]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [58]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  1],
       [ 4,  0]], dtype=int64)

In [59]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

### 配列の形状変更
* 配列の形状変更はreshapeメソッドを使う

In [60]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* 注意として最初の配列の要素数と、変更後の要素数が一致しないといけない
* reshapeメソッドは、可能であれば初期配列のコピー出なくビューを返す

In [61]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # reshapeを用いた行ベクトルの作成

array([[1, 2, 3]])

In [62]:
x.reshape((3, 1)) # reshapeを用いた列ベクトルの作成

array([[1],
       [2],
       [3]])

* スライスにnp.newaxisを組み合わせて同じ操作ができる

In [63]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [64]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])