# NumPy

In [1]:
import numpy
numpy.__version__

'1.26.4'

## Pythonのデータ型

In [2]:
# Pythonコード
result = 0
for i in range(100):
    result += i

* pythonでは、1つの整数変数は4つの部品から構成されている

```text
    ob_refcnt
        Pythonがメモリの割り当てと解除を自動的に行うための参照カウンタ
    ob_type
        変数の型を表すコード
    ob_size
        この後に続くデータの大きさ
    ob_digit
        このPython変数が持つ実際の整数値
```


In [3]:
# Pythonの型固定配列
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 'i'は整数型

In [4]:
# numpyの型固定配列
import numpy as np
# Integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

* Pythonリストとは異なりNumPy配列の要素はすべて同じ型という制約がある
* 型が一致しない場合、可能であればNumpyはアップキャストする(下記は整数から浮動小数点数)

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
# データ型の指定
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# 多次元の配列
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## NumPy配列の作成

* 大きな配列の場合、NumPyに組み込まれた関数を使用して配列を最初から作成する方が効率的。

In [8]:
# 要素がすべて0で長さ10の整数配列を作る
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 要素がすべて1である3行5列の浮動小数点配列を作る
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 要素がすべて3.14である3行5列の配列を作る
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# 開始値0、終了値20で2ずつ増加する
# 線形シーケンス配列を作る
# (組み込みのrange()関数と同じ働きをする)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# 0と1の間に均等に配置された5つの値の配列を作る
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# 0と1の間に3行3列の一様分布疑似乱数配列を作る
np.random.random((3,3))

array([[0.02987645, 0.29339343, 0.48571721],
       [0.32612828, 0.94313469, 0.94580737],
       [0.12609441, 0.56351172, 0.86197609]])

In [15]:
# 平均値0と標準偏差1の正規分布乱数で3行3列の配列を作る
np.random.normal(0, 1, (3, 3))

array([[-0.26996376, -0.30983483,  0.22383342],
       [ 1.43428712,  0.43217652, -0.61621997],
       [-0.64956371,  1.12434635, -2.51590814]])

In [16]:
# 区間[0, 10]のランダムな整数で3行3列の配列を作る
np.random.randint(0, 10, (3, 3))

array([[3, 9, 9],
       [1, 8, 2],
       [1, 7, 0]])

In [17]:
# 3行3列の単位行列を作る
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# 3つの整数の初期化されていない配列を作る
# 各要素の数は、そのメモリ位置に既に存在していたものになる
np.empty(3)

array([1., 1., 1.])

## NumPyの標準データ型
* NumPy配列の値はすべて同じ型
* 文字列で指定 or NumPyオブジェクトを使用する
    ```Python
    np.zeros(10, dtype='int16')
    # or
    np.zeros(10, dtype=np.int16)
    ```

* NumPyデータ型
  * 論理型
    * bool_ : 論理型(True or False) 1バイトに格納される
  * 整数型
    * int_ : デフォルトの整数型(C言語のlong)
    * intc : C言語のintと同じ
    * intp : インデクスに使用するための整数(C言語のssize_tと同様。通常int64 or int32)
    * int8 : -128から127
    * int16 : -32,768から32,767
    * int32 : -2,147,483,648から2,147,483,647
    * int64 : -9,223,372,036,854,775,808から9,223,372,036,854,775,807
  * 整数型(自然数)
    * uint8 : 0から255
    * uint16 : 0から65,535
    * uint32 : 0から4,294,967,295
    * uint64 : 0から18,446,744,073,709,551,615
  * 浮動小数点数型
    * float_ : float64の略
    * float16 : 符号部1ビット, 指数部5ビット, 仮数部10ビット
    * float32 : 符号部1ビット, 指数部8ビット, 仮数部23ビット
    * float16 : 符号部1ビット, 指数部11ビット, 仮数部52ビット
